### ISSUE TITLE
What should be mapped?

### ISSUE THREAD

**Issue by Locke** [MRVDH/mapping-north-korea#52]
In the HOT Tasking Manager each project has a detailed description of the entities to be mapped (roads, waterways, land uses, buildings).

I can not see any any explanation of things to be mapped with this project. I assume each sector should be mapped completely, including all roads, waterways and buildings? If this is true it should be noted on the About page more explicitly than "mapping everything" in the first sentence.

From my experience with HOT it leads to an inconsistent data set when too much different things are mapped at once and it's too easy to get lost in details of one area while missing basic elements in others.

I personally see not much value when individual residential buildings would be mapped before the basic road network.

I don't know the current mapping quality in North Korea [1], but I suggest that the mapping phases should concentrate on different features, for example:

- phase 1: important roads (unclassified / tertiary - but not residential / service) & important waterways (river / riverbed - but not stream / ditch) & important landuses (residential / industrial - but not farmland)
- phase 2: residential roads and smaller waterways in urban areas (important for bridges)
- phase 3: buildings

[1] I randomly zoomed to https://www.openstreetmap.org/#map=16/39.1644/126.2312 and noticed that this area should be connected with a road and have a residential landuse at least

**Comment by MRVDH** [comment]
I have been thinking about this as well lately. Currently no description is given as I kind of considered it to be up to people's own interpretation. What this means is that people can decide by themselves how much they want to map, and others can review if they think it's enough or if they want to add more. Person A might also want or like to add more than person B. I personally map ways, landuse and buildings. Example: [https://mappingnorthkorea.com/map/5c93aebb02ed1b2be46dce7b](https://mappingnorthkorea.com/map/5c93aebb02ed1b2be46dce7b). But I have seen others who just do main roads and waterways, or important pieces of landuse similar to how you described phase 1 and 2.

So the main reason I haven't added mapping descriptions yet is because I think mapping is most fun when you can kind of map as you like. Having the freedom and not being restricted to a specific rule set.

I like your setup of the three different phases and I think that maybe this is a good guideline for people who prefer to have it written out rather than leave it up to themselves to decide what to map, but I also think that if people want to map more than they should be allowed to do that as well. Maybe I should add a section for what to map and let people know what the target for this iteration is but that they are also free to map more than just that. I'm interested in hearing your take on this!

**Comment by Locke** [comment]
I should have some time next week to formulate some ideas.

**Comment by Ukundji** [comment]
I wrote a OSM message to MRVDH (and got a very pronmt, detailed answer) suggesting some similar ideas like Locke. I think that a more organized mapping would indeed be good/necessary if we want to see some crowd action to have much better maps in North Korea. In this case I would suggest to start with a certain area/county (or a few of them) in order to develop the project area by area, like the HOT task manager projects use to do.
Right now I understand that you, MRVDH want to encourage (some or a lot) mappers to do more mapping in North Korea just in the way and in the area they prefer. That is fine as well and if I am honest than this meets much more my "mapping style" and my motivation patterns. But in this case it would be great of we would have a kind of blog (accessable with a normal PC without Github account) in which mapping examples, mapping questions, discssions, statistics (like what has been done in "Mapping North Korea" last week?). Such a blog would draw the attention of parts of the community to this great project. I might be able to cintrubute to such a blog from time to time. 
Just my ideas and thoughts.

**Comment by MRVDH** [comment]
The application is built in this structure:

Iteration -> SectorSet -> Sector

Each sector is part of a sector set and each sector set is part of an iteration. I choose this design as I already thought of implementing something like this in the future. Currently there is only one sector set and one iteration. All the sectors you see are part of that one sector set.

What I could do is divide all the sectors into new sector sets that each represent a first level division of North Korea[1]. I could also make the sectors three times as small. For exceptional areas like cities we can manually split it into smaller pieces. A split tool is already implemented but only accessible by me to avoid abuse.

Do you think the sector sets should be on first-level divisions[1] or on second-level divisions[2]? Alternatively I could also do this:
Iteration | SectorSet | SectorSet | Sector
Mapping North Korea: Roads Iteration | first-level divisions | second-level divisions | Sectors

[1] https://en.wikipedia.org/wiki/Administrative_divisions_of_North_Korea#First-level_divisions
[2] https://en.wikipedia.org/wiki/List_of_second-level_administrative_divisions_of_North_Korea

**Comment by Ukundji** [comment]
It would be great and very much appreciated if you could install sector sets at the second-level-divisions. The kun (county) I am mapped in at the moment is Sakchu, North P'yŏngan province with some 160.000 inhabitants on 2.800 square kilometer. that`s quite a bit, but I think that most of the kuns are (much) smaller, though.
Thank yiou for you efforts and for your dedication.

**Comment by MRVDH** [comment]
Instead of making a sector set a child of another sector set, I think I will just keep it as Iteration -> sector set -> sector. Implementation-wise it could get quite complicated if I make a sector set a child of another sector set.

Having decided this, I am not sure how I will divide the sector sets. For example: a sector could be present in two or three second level divisions if the sector is on an administrative border[1]. Does that mean that you add that sector to both sector sets?

Right now a sector holds a reference to a sector set that it is part of. Currently this field only allows one value. I could however make it list instead of a single value so that each sector can be part of more than one sector set. What do you think?

[1] https://mappingnorthkorea.com/map/5c93aebb02ed1b2be46dbd06

**Comment by Ukundji** [comment]
Well, I am afraid that I am not the perfect discussion partner for technical and implementation issues. My focus is on the practical process of mapping plus cultural, geographical background. I like to "dive into" a certain area in order to understand as much as I can in order to improve the quality of mapping - realizing how limited my real knowledge as a remote mapper is.

Having said this I still want to try to abswer your question. I would include a certain sector only in one sector set. Otherwise you might end up with confusions. Even if the secor sets follow (roughly) the border of administrative units, I would simlify the borders so that a certain sector can only be on one side of an adminstrative border.

For the oceans we only need sector sets of there is something to map at all (islands, islets, ...)

**Comment by MRVDH** [comment]
The last two weeks I've been working on implementing all of this. The regions you see are the counties.

![image](https://user-images.githubusercontent.com/6686385/98556325-39394400-22a3-11eb-9f81-f78a080677d6.png)

I'm currently working on being able to click on a county and see all the individual sectors. This comment will be updated to show the progress.

**Comment by MRVDH** [comment]
Update (still unreleased)

Finished most of the new layout. Now going to make sure that all the already done sectors are marked as "done" and with the same events as from the 'old' data set. Dividing everything in larger sector sets also had the nice effect of the site loading much faster.

![2020-11-12_09-06-50](https://user-images.githubusercontent.com/6686385/98912659-aed12a00-24c6-11eb-9eb4-acc05cedef25.gif)

**Comment by MRVDH** [comment]
I've finished it, but I'm running into issues with the deployment. The site is therefore temporarily unreachable.

https://www.digitalocean.com/community/questions/app-platform-out-of-memory-on-deploy

**Comment by MRVDH** [comment]
The new version is now live. Closing this issue 👍
