### ISSUE TITLE
Show selected area in iD

### ISSUE THREAD

**Issue by tordans** [MRVDH/mapping-north-korea#54]
The Tasking Manager shows a ping square in iD which shows me the area I selected to map. 

I missed this when I „viewed“ an area out of interest.

It helps to connect the editor with the task manager.

**Comment by MRVDH** [comment]
Correct! I can only show the pink area when you go to iD with the "Map" button, but not with the "View" button.

The difference:
"Map" opens the iD editor with a GPX coordinates set that displays the pink square.
"View" just opens the main OpenStreetMap site.

I have not found a way to show a pink GPX square with the OpenStreetMap website. I think it's simply not possible.

**Comment by MRVDH** [comment]
I just added it as a suggestion to the OSM website!
https://github.com/openstreetmap/openstreetmap-website/issues/2275

**Comment by tordans** [comment]
Thanks, I must have overlooked the fact, that the app opens the view-view first.
I suggest removing this feature. If I want to see the the view-view, I can just zoom into your app. Its the same data and view. Maybe a bit less visible due to the colored overlay, but still, the view-view on osm-org does not provide additional information.

---

Side note for #2275: The `gpx`-param should also be added to the Edit-URL. Otherwise the area gets lost between the view and the edit action.

**Comment by MRVDH** [comment]
The gpx param is added to the edit URL but iD removes the gpx param once the track and page have been loaded.

Could you explain what you mean by "the app opens the view-view first"? Regarding the buttons; the map button is disabled until you login and the sector is set to an editable state. Therefore we have the view button so that you can still look at it on OSM or edit it there in case you need to.
![image](https://user-images.githubusercontent.com/6686385/59994261-7de32180-9653-11e9-94bf-54bf9fa28234.png)

Not closing it yet as I would like to hear your view on this a bit more :)

**Comment by MRVDH** [comment]
Closing since OSM will not implement gpx on their basemap requests. I agree with you and will think of a nicer solution. :)
