### ISSUE TITLE
Map using JOSM remote control not working

### ISSUE THREAD

**Issue by claudiush** [MRVDH/mapping-north-korea#62]
How to reproduce:
- Have JOSM open with Remote Control enabled and the local HTTPS certificate installed
- On https://mappingnorthkorea.com select a tile in editing mode 
- Select "JOSM" from the "Map" button menu.

Expected result:
JOSM to load the area to map

Result:
MNK shows this error toast:
![image](https://user-images.githubusercontent.com/428616/62615644-f2c1a080-b90d-11e9-83b3-f8f48ad9b556.png)
Nothing happens in JOSM

Tried with Chrome 74 and Edge 44 on Windows 10

**Comment by MRVDH** [comment]
This is the code that makes the connection with JOSM:

```js
        mapSectorInJOSM () {
            var loadAndZoomParams = {
                left: this.selectedSector.geometry.coordinates[0][0][0],
                bottom: this.selectedSector.geometry.coordinates[0][2][1],
                right: this.selectedSector.geometry.coordinates[0][1][0],
                top: this.selectedSector.geometry.coordinates[0][0][1],
                changeset_comment: encodeURIComponent('MappingNorthKorea.com sector ' + this.selectedSector.properties._id)
            };
            EventBus.$emit('mnk:start-loading', 'sendJOSMCommand');
            JOSMService.sendJOSMCommand('https://127.0.0.1:8112/load_and_zoom', loadAndZoomParams).catch(() => {
                EventBus.$emit('mnk:message-error', this.$t('request.josm_failed'));
                EventBus.$emit('mnk:stop-loading', 'sendJOSMCommand');
            });
            JOSMService.sendJOSMCommand('https://127.0.0.1:8112/imagery', {
                type: 'bing',
                url: 'https://www.bing.com/maps/'
            });
        },
```

Could you check if the url and port are the same as your settings in JOSM?
`https://127.0.0.1:8112/`

**Comment by 7RST1** [comment]
Same issue here.
Tried with Chromium and Firefox on Linux (Pop!_OS 19.04). If i go to the address, the page goes black so the remote control address is open.

**Comment by MRVDH** [comment]
> Same issue here.
> Tried with Chromium and Firefox on Linux (Pop!_OS 19.04). If i go to the address, the page goes black so the remote control address is open.

Thanks for that info! Every bit helps to debug. I'm leaving tomorrow so I'll post here (and on telegram) once I figure it out after my holidays.

Also feel free to debug it yourself and open a pull request of course!

**Comment by claudiush** [comment]
Confirming that port 8112 is my HTTPS port for JOSM remote control.
Looking at how OSM Inspector does it they seem to be assigning the localhost remote control call to an invisible iframe on the page which doesn't seem to trigger the net::ERR_CONNECTION_REFUSED your code is running into.

**Comment by wetneb** [comment]
In my case, it was just because JOSM uses a self-signed certificate that Firefox blocks by default. To solve this:
* Go to https://127.0.0.1:8112/ with your browser;
* Add a security exception to accept the self-signed certificate;
* Try editing a sector with JOSM again.

I am not sure why MappingNorthKorea connects to JOSM in HTTPS - I expect using HTTP would solve the problem (HTTP calls to localhost should not be blocked by the browser even if the originating page is HTTPS, in my experience).

**Comment by MRVDH** [comment]
I've been able to reproduce this on Firefox but not on Chrome. @wetneb 's solution seems to work for me as well. I'd like to find a way to fix this in a different way though. I'll look into how other applications do it.

**Comment by MRVDH** [comment]
> I am not sure why MappingNorthKorea connects to JOSM in HTTPS - I expect using HTTP would solve the problem (HTTP calls to localhost should not be blocked by the browser even if the originating page is HTTPS, in my experience).

It's because the website uses HTTPS as well. I remember during testing that I has issues with not using HTTPS to connect to JOSM. However, if it would solve these issues then I could give plain HTTP another shot. The information sent to JOSM is not privacy sensitive anyway (just a bounding box and a sector ID comment)

**Comment by MRVDH** [comment]
I've tried it without HTTPS and it gives me this as a response `�`

**Comment by MRVDH** [comment]
Tried doing it through an iframe like the HOT Tasking Manager does, but no success either. I think I will just keep it as it is and put a link in the error message that goes to the FAQ or a help page that tells the user to open the link in a new tab.

**Comment by 7RST1** [comment]
I request to reopen this issue. JOSM no longer listens at port 8112 as it dropped HTTPS support a month after this issue was closed. ([ticket](https://josm.openstreetmap.de/changeset/15469/josm). The HTTPS option is no longer present in the Remote Control settings in JOSM and the port is not open when i try connecting to it. I think the website has to switch to http (8111) to fix JOSM remote control support.

**Comment by MRVDH** [comment]
Thanks @7RST1 for reporting this! The pull request you mentioned did indeed partially fix it, but the build command wasn't run and there was a parsing error, therefore the fix was never applied. I should have noticed this earlier!

I fixed it in the latest pull request, and the changes should be live now. :)

**Comment by MRVDH** [comment]
I can confirm that it works again :)

![image](https://user-images.githubusercontent.com/6686385/71956473-91b73500-31eb-11ea-96cf-e973a0560e63.png)

![image](https://user-images.githubusercontent.com/6686385/71956481-98de4300-31eb-11ea-91f9-62d05842464c.png)
